language: python
python:
  - "2.7"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - sudo apt-get update
  - echo $TRAVIS_PYTHON_VERSION
script:
  - export S2_TOA_TO_LAI_VERSION=$TRAVIS_TAG
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  skip_existing: true
  on:
    branch: master
