language: python
python:
  - "2.7"
  - "3.6"
install:
  - sudo apt-get update
  - echo $TRAVIS_PYTHON_VERSION
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  skip_existing: true
  on:
    branch: master
