package:
  name: toa2lai
  version: {{ environ['S2_TOA_TO_LAI_VERSION'] }}
     
source:
  path: ./

build:
  script: python setup.py install  --single-version-externally-managed --record=record.txt
  noarch: generic
  channels:
    - anaconda
    - conda-forge
  script_env:
    - VERSION
    - CONDA_BLD_PATH
     
requirements:
  host:
    - python
    - conda-build >=2.1
    - gdal >=2.1,<2.4
  run:
    - python
    - conda-build >=2.1
    - gdal >=2.1,<2.4
test:
  commands:
    - echo 'Hello world'
about:
  home: https://github.com/MarcYin/S2_TOA_TO_LAI.git
  license: GNU Affero General Public License v3.0
  license_family: AGPL
  license_file: 'LICENSE.md'
  summary:  From Sentinel 2 TOA to LAI
  description: "From Sentinel 2 TOA to LAI"
  doc_url: ''
  dev_url: ''
     
extra:
  recipe-maintainers: ''
